### ISSUE TITLE
fatal error: sync: Unlock of unlocked RWMutex

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/gorouter#223]
## Issue

Today one of our gorouters failed and exiitted with a fatal error: `fatal error: sync: Unlock of unlocked RWMutex` 

The process got restarted by monit immediately after, and started to serve normally.

All active connections got canceled with a 503 (likely from the haproxy we have in front)

## Context

Running cf-deployment v2.6.0 with cf-routing-release v0.179.0 (which is the gorouter commit 3502659a1524fcff918c8a4396ac5440e0551156) 

## Steps to Reproduce

NaN, failed during normal operation

## Expected result
no failure
## Current result

Process died with this stacktrace:

https://gist.github.com/keymon/7fc6a2c21442651707e847cb3023d487

First lines:
```
[2018-08-13 14:46:48+0000] fatal error: sync: Unlock of unlocked RWMutex
[2018-08-13 14:46:48+0000] 
[2018-08-13 14:46:48+0000] goroutine 68250842 [running]:
[2018-08-13 14:46:48+0000] runtime.throw(0xa72d45, 0x20)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/packages/golang-1.9-linux/88a7626f51143d021545ce3f6ac2a6ed44766aed/src/runtime/panic.go:605 +0x95 fp=0xc4221274b8 sp=0xc422127498 pc=0x42d615
[2018-08-13 14:46:48+0000] sync.throw(0xa72d45, 0x20)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/packages/golang-1.9-linux/88a7626f51143d021545ce3f6ac2a6ed44766aed/src/runtime/panic.go:594 +0x35 fp=0xc4221274d8 sp=0xc4221274b8 pc=0x42d575
[2018-08-13 14:46:48+0000] sync.(*RWMutex).Unlock(0xc420d9d590)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/packages/golang-1.9-linux/88a7626f51143d021545ce3f6ac2a6ed44766aed/src/sync/rwmutex.go:125 +0xa1 fp=0xc422127508 sp=0xc4221274d8 pc=0x475131
[2018-08-13 14:46:48+0000] code.cloudfoundry.org/gorouter/route.(*RoundRobin).Next(0xc42034f260, 0xc420d9d590)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/route/roundrobin.go:44 +0x1aa fp=0xc422127550 sp=0xc422127508 pc=0x76652a
[2018-08-13 14:46:48+0000] code.cloudfoundry.org/gorouter/proxy/round_tripper.(*roundTripper).selectEndpoint(0xc42060a580, 0xd77080, 0xc42034f260, 0xc420d40700, 0xc420259400, 0x1, 0x1)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/proxy/round_tripper/proxy_round_tripper.go:282 +0x31 fp=0xc422127570 sp=0xc422127550 pc=0x8d71e1
[2018-08-13 14:46:48+0000] code.cloudfoundry.org/gorouter/proxy/round_tripper.(*roundTripper).RoundTrip(0xc42060a580, 0xc420d40700, 0x0, 0x0, 0x0)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/proxy/round_tripper/proxy_round_tripper.go:130 +0xe07 fp=0xc422127da8 sp=0xc422127570 pc=0x8d5d77
[2018-08-13 14:46:48+0000] net/http/httputil.(*ReverseProxy).ServeHTTP(0xc4200547c0, 0xd74680, 0xc42096fcc0, 0xc420d40600)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/packages/golang-1.9-linux/88a7626f51143d021545ce3f6ac2a6ed44766aed/src/net/http/httputil/reverseproxy.go:201 +0x2dd fp=0xc422127fe0 sp=0xc422127da8 pc=0x8bba1d
[2018-08-13 14:46:48+0000] github.com/urfave/negroni.Wrap.func1(0xd74680, 0xc42096fcc0, 0xc420d40600, 0xc42034f240)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:41 +0x4d fp=0xc422128010 sp=0xc422127fe0 pc=0x8bf01d
[2018-08-13 14:46:48+0000] github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc420362820, 0xd74680, 0xc42096fcc0, 0xc420d40600, 0xc42034f240)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:24 +0x4e fp=0xc422128040 sp=0xc422128010 pc=0x8bdefe
[2018-08-13 14:46:48+0000] github.com/urfave/negroni.middleware.ServeHTTP(0xd700c0, 0xc420362820, 0xc420362a40, 0xd74680, 0xc42096fcc0, 0xc420d40600)
[2018-08-13 14:46:48+0000] 	/var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0xa5 fp=0xc422128090 sp=0xc422128040 pc=0x8bdfb5
[2018-08-13 14:46:48+0000] github.com/urfave/negroni.(middleware).ServeHTTP-fm(0xd74680, 0xc42096fcc0, 0xc420d40600)
....
```

**Comment by KauzClay** [comment]
Without a way to reproduce this, we can't offer much help. We will close this but please reopen or open a new issue if the problem persists.

**Comment by keymon** [comment]
Hello, this happened again to us:

```
fatal error: sync: Unlock of unlocked RWMutex

goroutine 542353543 [running]:
runtime.throw(0xa7e293, 0x20)
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/runtime/panic.go:608 +0x72 fp=0xc001e63818 sp=0xc001e637e8 pc=0x42daf2
sync.throw(0xa7e293, 0x20)
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/runtime/panic.go:594 +0x35 fp=0xc001e63838 sp=0xc001e63818 pc=0x42da75
sync.(*RWMutex).Unlock(0xc0012241e0)
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/sync/rwmutex.go:124 +0xa1 fp=0xc001e63868 sp=0xc001e63838 pc=0x4741f1
code.cloudfoundry.org/gorouter/route.(*RoundRobin).Next(0xc000370580, 0xc0012241e0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/route/roundrobin.go:44 +0x190 fp=0xc001e638a0 sp=0xc001e63868 pc=0x78a150
code.cloudfoundry.org/gorouter/proxy/round_tripper.(*roundTripper).selectEndpoint(0xc00010a480, 0xb18160, 0xc000370580, 0xc001df0b00, 0xc0001e7a00, 0xa66ad6, 0x1)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/proxy/round_tripper/proxy_round_tripper.go:282 +0x31 fp=0xc001e638c0 sp=0xc001e638a0 pc=0x8e59a1
code.cloudfoundry.org/gorouter/proxy/round_tripper.(*roundTripper).RoundTrip(0xc00010a480, 0xc001df0b00, 0x0, 0x0, 0x0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/proxy/round_tripper/proxy_round_tripper.go:130 +0xd99 fp=0xc001e64060 sp=0xc001e638c0 pc=0x8e4199
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc00027d180, 0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/net/http/httputil/reverseproxy.go:232 +0x2ff fp=0xc001e642c0 sp=0xc001e64060 pc=0x8cb06f
github.com/urfave/negroni.Wrap.func1(0xb156a0, 0xc0014784c0, 0xc001df0a00, 0xc000370500)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:41 +0x4d fp=0xc001e642f0 sp=0xc001e642c0 pc=0x8ce75d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc00024be20, 0xb156a0, 0xc0014784c0, 0xc001df0a00, 0xc000370500)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:24 +0x4e fp=0xc001e64320 sp=0xc001e642f0 pc=0x8cd7fe
github.com/urfave/negroni.middleware.ServeHTTP(0xb11a60, 0xc00024be20, 0xc000254020, 0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e64358 sp=0xc001e64320 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64398 sp=0xc001e64358 pc=0x8ce920
code.cloudfoundry.org/gorouter/proxy.(*proxy).ServeHTTP(0xc00007d2b0, 0xb156a0, 0xc0014784c0, 0xc001df0a00, 0xc000370400)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/proxy/proxy.go:233 +0x519 fp=0xc001e64588 sp=0xc001e64398 pc=0x8e86c9
github.com/urfave/negroni.middleware.ServeHTTP(0xb10500, 0xc00007d2b0, 0xc000254000, 0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e645c0 sp=0xc001e64588 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64600 sp=0xc001e645c0 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*RouteService).ServeHTTP(0xc0001f9530, 0xb156a0, 0xc0014784c0, 0xc001df0a00, 0xc0003703e0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/routeservice.go:46 +0xe2e fp=0xc001e649a8 sp=0xc001e64600 pc=0x8dc58e
github.com/urfave/negroni.middleware.ServeHTTP(0xb102e0, 0xc0001f9530, 0xc00024bfe0, 0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e649e0 sp=0xc001e649a8 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001df0a00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64a20 sp=0xc001e649e0 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*XForwardedProto).ServeHTTP(0xc00024b860, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0003703c0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/x_forwarded_proto.go:43 +0x2b2 fp=0xc001e64af8 sp=0xc001e64a20 pc=0x8dd682
github.com/urfave/negroni.middleware.ServeHTTP(0xb10300, 0xc00024b860, 0xc00024bfc0, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e64b30 sp=0xc001e64af8 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64b70 sp=0xc001e64b30 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*clientCert).ServeHTTP(0xc0001f9650, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0003703a0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/clientcert.go:73 +0x4a5 fp=0xc001e64cc8 sp=0xc001e64b70 pc=0x8d82e5
github.com/urfave/negroni.middleware.ServeHTTP(0xb10360, 0xc0001f9650, 0xc00024bfa0, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e64d00 sp=0xc001e64cc8 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64d40 sp=0xc001e64d00 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*lookupHandler).ServeHTTP(0xc0001f95f0, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c44e0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/lookup.go:56 +0x2bc fp=0xc001e64e10 sp=0xc001e64d40 pc=0x8d983c
github.com/urfave/negroni.middleware.ServeHTTP(0xb103c0, 0xc0001f95f0, 0xc00024bf80, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e64e48 sp=0xc001e64e10 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64e88 sp=0xc001e64e48 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*protocolCheck).ServeHTTP(0xc00023de10, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c44c0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/protocolcheck.go:47 +0x18e fp=0xc001e64f00 sp=0xc001e64e88 pc=0x8da3ae
github.com/urfave/negroni.middleware.ServeHTTP(0xb103e0, 0xc00023de10, 0xc00024bf60, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e64f38 sp=0xc001e64f00 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e64f78 sp=0xc001e64f38 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*Zipkin).ServeHTTP(0xc0001f9560, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c4480)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/zipkin.go:64 +0x376 fp=0xc001e65158 sp=0xc001e64f78 pc=0x8ddb36
github.com/urfave/negroni.middleware.ServeHTTP(0xb10320, 0xc0001f9560, 0xc00024bf20, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e65190 sp=0xc001e65158 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e651d0 sp=0xc001e65190 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*proxyHealthcheck).ServeHTTP(0xc0001f95c0, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c4460)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/proxy_healthcheck.go:32 +0x8a fp=0xc001e65218 sp=0xc001e651d0 pc=0x8da58a
github.com/urfave/negroni.middleware.ServeHTTP(0xb10400, 0xc0001f95c0, 0xc00024bf00, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e65250 sp=0xc001e65218 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e65290 sp=0xc001e65250 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*reporterHandler).ServeHTTP(0xc00024b0c0, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c4440)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/reporter.go:31 +0x62 fp=0xc001e65380 sp=0xc001e65290 pc=0x8daa92
github.com/urfave/negroni.middleware.ServeHTTP(0xb10440, 0xc00024b0c0, 0xc00024bee0, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e653b8 sp=0xc001e65380 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e653f8 sp=0xc001e653b8 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*accessLog).ServeHTTP(0xc000182800, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c4400)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/access_log.go:50 +0x1a6 fp=0xc001e65610 sp=0xc001e653f8 pc=0x8d7a46
github.com/urfave/negroni.middleware.ServeHTTP(0xb10340, 0xc000182800, 0xc00024bec0, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e65648 sp=0xc001e65610 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e65688 sp=0xc001e65648 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*httpStartStopHandler).ServeHTTP(0xc00024af00, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c43e0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/httpstartstop.go:47 +0x2c1 fp=0xc001e65898 sp=0xc001e65688 pc=0x8d9101
github.com/urfave/negroni.middleware.ServeHTTP(0xb103a0, 0xc00024af00, 0xc00024bea0, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e658d0 sp=0xc001e65898 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e65910 sp=0xc001e658d0 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*setVcapRequestIdHeader).ServeHTTP(0xc00023dde0, 0xb156a0, 0xc0014784c0, 0xc001e37e00, 0xc0017c4300)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/request_id.go:38 +0x1c1 fp=0xc001e65a70 sp=0xc001e65910 pc=0x8dafb1
github.com/urfave/negroni.middleware.ServeHTTP(0xb10460, 0xc00023dde0, 0xc00024be80, 0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e65aa8 sp=0xc001e65a70 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0xb156a0, 0xc0014784c0, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e65ae8 sp=0xc001e65aa8 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*proxyWriterHandler).ServeHTTP(0xc00023ddd0, 0x7f33a811fcd0, 0xc001478480, 0xc001e37e00, 0xc0017c42e0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/proxywriter.go:34 +0x2b4 fp=0xc001e65bc8 sp=0xc001e65ae8 pc=0x8da9d4
github.com/urfave/negroni.middleware.ServeHTTP(0xb10420, 0xc00023ddd0, 0xc00024be60, 0x7f33a811fcd0, 0xc001478480, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e65c00 sp=0xc001e65bc8 pc=0x8cd8ac
github.com/urfave/negroni.middleware.ServeHTTP-fm(0x7f33a811fcd0, 0xc001478480, 0xc001e37e00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x60 fp=0xc001e65c40 sp=0xc001e65c00 pc=0x8ce920
code.cloudfoundry.org/gorouter/handlers.(*RequestInfoHandler).ServeHTTP(0xff6b88, 0x7f33a811fcd0, 0xc001478480, 0xc001e37d00, 0xc0017c42c0)
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/handlers/requestinfo.go:51 +0x186 fp=0xc001e65cb8 sp=0xc001e65c40 pc=0x8db3d6
github.com/urfave/negroni.middleware.ServeHTTP(0xb102a0, 0xff6b88, 0xc00024be40, 0x7f33a811fcd0, 0xc001478480, 0xc001e37d00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:33 +0x9c fp=0xc001e65cf0 sp=0xc001e65cb8 pc=0x8cd8ac
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0001f9590, 0xb17620, 0xc0002b0d20, 0xc001e37d00)
        /var/vcap/data/compile/gorouter/src/github.com/urfave/negroni/negroni.go:73 +0xbc fp=0xc001e65d48 sp=0xc001e65cf0 pc=0x8cdb4c
net/http.serverHandler.ServeHTTP(0xc000d92000, 0xb17620, 0xc0002b0d20, 0xc001e37d00)
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/net/http/server.go:2741 +0xab fp=0xc001e65d78 sp=0xc001e65d48 pc=0x69c28b
net/http.(*conn).serve(0xc0001b0640, 0xb181a0, 0xc0014783c0)
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/net/http/server.go:1847 +0x646 fp=0xc001e65fc8 sp=0xc001e65d78 pc=0x6986b6
runtime.goexit()
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc001e65fd0 sp=0xc001e65fc8 pc=0x45dde1
created by net/http.(*Server).Serve
        /var/vcap/data/packages/golang-1-linux/23000b162f4614e0091867cac7f369ae2cf23488/src/net/http/server.go:2851 +0x2f5

goroutine 1 [chan receive, 18397 minutes]:
main.main()
        /var/vcap/data/compile/gorouter/src/code.cloudfoundry.org/gorouter/main.go:195 +0x1a6a
```
